name: Publish Package

on:
	workflow_dispatch

jobs:
	build-and-publish:
		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v2
		- name: Setup .NET
			uses: actions/setup-dotnet@v1
			with:
				dotnet-version: 5.0.x
		- name: Restore dependencies
			run: dotnet restore
		- name: Build
			run: dotnet build --no-restore --configuration Release
		- name: Test
			run: dotnet test --no-build --configuration Release --verbosity normal
		- name: Pack
			run: dotnet pack --no-build --configuration Release
		- name: Push
			run: dotnet nuget push "*.nupkg" --skip-duplicate --no-symbals true --api-key ${{secrets.NUGET_TOKEN}}
